### ISSUE TITLE
Stats tab

### ISSUE THREAD

**Issue by Tragedy-dev** [earthernsence/baba-make-cash-dev#4]
it would be nice if in the stats page it displayed your amount of hired Kekes and how many upgrades have been bought.

**Comment by Tragedy-dev** [comment]
I mean, it *is* a statistic imo
~~also I'm totally not using this to talk in #bmc-commits~~

**Comment by earthernsence** [comment]
also use the template goddammit

**Comment by Tragedy-dev** [comment]
yeah I saw that and it was quite large so I just deleted everything and figured a small suggestion didn't need a screenshot an all that
